<?php

namespace App\Console\Commands\Kernel;

use App\Console\Files\Generator;

class GenerateMigration extends Generator
{
    public $command = "gen:migration";
    public $description = "generate a migrations class";
    public $options = [
        "-n" => "name of migration"
    ];

    private const FILE = 'AutoGenerated';

    protected function namespace (): string
    {
        return config("database.migration.namespace");
    }

    protected function stub(): string
    {
        return resource('stubs/migration.stub');
    }

    private function generateName(?string $name): string
    {
        return $name ?? self::FILE . "_" . time();
    }

    protected function name(): string
    {
        return $this->generateName($this->option("n"));
    }

    protected function folder(): string
    {
        return config("database.migration.path");
    }
}
