version: '3'
services:
  app:
    container_name: app
    working_dir: /var/www/html
    build: ./build
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - rabbitmq
    env_file: 
      - ./.env
    networks:
      - framework
  rabbitmq:
    container_name: app_rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - framework
  db:
    image: mysql:8.0.0
    container_name: app_db
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - framework
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  framework: 
    driver: bridge
    name: framework
volumes:
  database:
