<?php

namespace Database\Migrations;

use QueryBuilder\Macro\Schemma\Columns;

class AutoGenerated1708090739 extends \Database\Migration
{
    public function up(): void 
    {
        $this->create()->table('product_log')->columns(function (Columns $col){
            $col->add('id')->int(8)->autoIncrement()->primaryKey();
            $col->add('product_id')->int(8)->notNull();
            $col->add('web_source_id')->int(8)->notNull();
            $col->add('status')->varchar(255)->default("'ACTIVE'");
            $col->add('message')->text();
            $col->add('created_at')->dateTime();
            $col->add('updated_at')->dateTime();
            $col->constraint('fk_pl_product_id')->fk('product_id')->references('products', 'id');
            $col->constraint('fk_pl_web_source_id')->fk('web_source_id')->references('web_source', 'id');
            return $col;
        })->execute();
    }

    public function down(): void
    {
        $this->raw("DROP TABLE IF EXISTS `product_log`");
    }

    public function bindSeeds(): array 
    {
        return [
            //
        ];
    }
}