<?php

namespace Database\Migrations;

use QueryBuilder\Macro\Schemma\Columns;

class AutoGenerated1707829916 extends \Database\Migration
{
    public function up(): void
    {
        $this->create()->table('web_source')->columns(function (Columns $col) {
            $col->add('id')->int(8)->autoIncrement()->primaryKey();
            $col->add('name')->varchar(255)->notNull();
            $col->add('logo_path')->varchar(255);
            $col->add('created_at')->datetime();
            $col->add('domain')->varchar(255)->notNull();
            $col->add('updated_at')->datetime()->default('NULL');
            $col->add('deleted_at')->datetime()->default('NULL');
            return $col;
        })->execute();
    }

    public function down(): void
    {
        $this->raw('DROP TABLE web_source')->execute();
    }

    public function bindSeeds(): array
    {
        return [
            //
        ];
    }
}