<?php

namespace Database\Migrations;

use Database\Seeds\Users;
use QueryBuilder\Macro\Schemma\Columns;

class AutoGenerated1707485503 extends \Database\Migration
{
    public function up(): void
    {
        $this->create()->table("users")->columns(function (Columns $col) {
            $col->add("id")->int(8)->autoIncrement()->primaryKey();
            $col->add("email")->varchar(100)->notNull();
            $col->add("password")->varchar(100)->notNull();
            $col->add("created_at")->datetime()->default("null");
            $col->add("updated_at")->datetime()->default("null");
            $col->add("deleted_at")->datetime()->default("null");
            return $col;
        })->execute();
    }

    public function down(): void
    {
        $this->raw("DROP TABLE users;");
    }

    public function bindSeeds(): array
    {
        return [
            Users::class
        ];
    }
}