<?php

return [
    "url" => CURLOPT_URL,
    "returnTransfer" => CURLOPT_RETURNTRANSFER,
    "post" => CURLOPT_POST,
    "postFields" => CURLOPT_POSTFIELDS,
    "httpHeader" => CURLOPT_HTTPHEADER,
    "customRequest" => CURLOPT_CUSTOMREQUEST,
    "userAgent" => CURLOPT_USERAGENT,
    "followLocation" => CURLOPT_FOLLOWLOCATION,
    "maxRedirects" => CURLOPT_MAXREDIRS,
    "sslVerifyPeer" => CURLOPT_SSL_VERIFYPEER,
    "sslVerifyHost" => CURLOPT_SSL_VERIFYHOST,
    "caInfo" => CURLOPT_CAINFO,
    "timeout" => CURLOPT_TIMEOUT,
    "connectTimeout" => CURLOPT_CONNECTTIMEOUT,
    "header" => CURLOPT_HEADER,
    "nobody" => CURLOPT_NOBODY,
    "port" => CURLOPT_PORT,
    "proxy" => CURLOPT_PROXY,
    "proxyPort" => CURLOPT_PROXYPORT,
    "proxyUserPwd" => CURLOPT_PROXYUSERPWD,
    "cookie" => CURLOPT_COOKIE,
    "cookieJar" => CURLOPT_COOKIEJAR,
    "cookieFile" => CURLOPT_COOKIEFILE,
    "referer" => CURLOPT_REFERER,
    "acceptEncoding" => CURLOPT_ACCEPT_ENCODING,
    "encoding" => CURLOPT_ENCODING,
    "autoReferer" => CURLOPT_AUTOREFERER,
    "userPwd" => CURLOPT_USERPWD,
    "httpAuth" => CURLOPT_HTTPAUTH,
    "file" => CURLOPT_FILE,
    "inFile" => CURLOPT_INFILE
];